{
    "name": "Garments Compliance Management",
    "version": "18.0.4.2.0",
    "category": "Manufacturing/Compliance",
    "summary": "Buyer audits (BSCI/WRAP/SEDEX) and full factory compliance management",
    "author": "Custom",
    "license": "LGPL-3",
    "depends": ["base", "mail", "hr", "web"],
    "data": [
        "security/compliance_security.xml",
        "security/ir.model.access.csv",
        "data/sequence.xml",
        "data/grade_data.xml",
        "data/standard_data.xml",
        "data/buyer_program_data.xml",
        "data/cron.xml",
        "views/master_views.xml",
        "views/standard_views.xml",
        "views/actions.xml",
        "views/audit_views.xml",
        "views/finding_views.xml",
        "views/register_views.xml",
        "views/hr_compliance_views.xml",
        "report/audit_report.xml",
        "views/compliance_menus.xml",
    ],
    "demo": ["demo/demo_data.xml"],
    "assets": {"web.assets_backend": [
        "garments_compliance/static/src/js/compliance_dashboard.js",
        "garments_compliance/static/src/xml/compliance_dashboard.xml",
        "garments_compliance/static/src/css/compliance_dashboard.css",
    ]},
    "application": True,
    "installable": True,
}
